# CI workflow to enforce required "build" check for branch protection

name: CI

# Trigger on pull request events
on:
  pull_request:

# Minimal permissions for security
permissions:
  contents: read

jobs:
  build:                     # Job name must match REQUIRED_CHECK_NAME=build
    runs-on: ubuntu-latest   # Use latest Ubuntu runner
    timeout-minutes: 20      # Cancel job if it runs too long

    concurrency:             # Auto-cancel older runs of same PR branch
      group: pr-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0     # Fetch full history (GitLab: build_git_strategy: fetch)

      - uses: actions/cache@v4
        with:
          path: ~/.cache/yourtool
          key: build-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml', '**/poetry.lock', '**/requirements*.txt') }}  # Separate caches per branch

      - name: Run build/test
        run: |
          echo "Run your build/tests here"  # Replace with actual build/test commands
